console.log("welcome to my website")
console.log("hallo")
console.log("this website only for abid friend")
console.log("play and enjoy")
console.log("made by toky intelligent best smart gamer")
console.log("gamertoky1188gro")
console.log("gamertoky1188")
console.log("tasnim mahamud jahin")
console.log("toky")